### PR TITLE
feat: support kubernetes 1.27

### PR DESCRIPTION
**Pull request by ajgon**
This is the initial draft, attempting to solve #139 . I'll do a extensive testing on my cluster, later this day, and adapt PR if I find any other issues.

### CODE REVIEW

**Comment by Sycrosity** [comment]
Any update on this? Take all the time you need just wondering what the status of the PR is.

**Comment by alex1989hu** [comment]
@Sycrosity https://github.com/alex1989hu/kubelet-serving-cert-approver/issues/139#issuecomment-1519682974

**Comment by Sycrosity** [comment]
@alex1989hu ah yes sorry I thought this PR was still happening despite the plan to wait for https://github.com/kubernetes-sigs/controller-runtime/pull/2189 - my misunderstanding

**Comment by alex1989hu** [comment]
Dear @ajgon @Sycrosity I have just released https://github.com/alex1989hu/kubelet-serving-cert-approver/releases/tag/v0.7.0

**Pull request closed without merging**
